### PR TITLE
Fix/distribute contract balance setup

### PR DESCRIPTION
**Pull request by uranium93**
The tests are failing because the contract instance is always with balance=0 means that the transfer is sending zero values

Not sure if this was intentional and part of the puzzle, if it's the case let me know and I will delete the MR

### CODE REVIEW

**Comment by uranium93** [comment]
It includes changes from #16

**Comment by 3fOhorky** [comment]
It does seem odd that the constructor is payable but no value is sent with it. Although this kind of change enables another solution of Distribute puzzle as far as I can see.

**Comment by burke-md** [comment]
@uranium93 Looks good - Pease pull the changes on the main branch into yours and squash your commits. We'll get this merged in.

**Comment by uranium93** [comment]
@burke-md, sorry for the later response; I resolved the conflict and pushed.

I didn't get the part about squashing my commits, I believe you can squash them when merging with the main, or do you want me to create a new branch and rebase all in one commit?

**Pull request merged**
